# Generated by Django 4.1.1 on 2022-09-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.CharField(max_length=50)),
                ('descrition', models.TextField()),
                ('hobby_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('grade', models.PositiveIntegerField(default=0)),
                ('hobby', models.ForeignKey(db_column='hobby_id', on_delete=django.db.models.deletion.CASCADE, related_name='hobbys', to='main.hobby')),
            ],
        ),
    ]
