# Generated by Django 4.1.1 on 2022-10-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
