# Generated by Django 4.1.1 on 2022-10-13 13:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_image',
            field=models.ImageField(blank=True, upload_to=main.models.image_upload_path),
        ),
    ]
