# Generated by Django 4.1.1 on 2022-09-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='hobby_name',
            new_name='hobby_title',
        ),
    ]
