# Generated by Django 4.1.1 on 2022-10-17 03:58

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='hobby_image',
        ),
        migrations.CreateModel(
            name='HobbyImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to=main.models.image_upload_path)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.hobby')),
            ],
            options={
                'db_table': 'hobby_image',
            },
        ),
    ]
