# Generated by Django 4.1.1 on 2022-09-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_hobby_name_hobby_hobby_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='hobby',
            new_name='hobby_id',
        ),
    ]
