# Generated by Django 4.1.1 on 2022-10-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_review_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hobby_rv',
            field=models.ForeignKey(blank=True, db_column='hobby_rv', on_delete=django.db.models.deletion.CASCADE, related_name='hobby_rv', to='main.hobby'),
        ),
    ]
