# Generated by Django 4.1.1 on 2022-10-26 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_pd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('price', models.IntegerField()),
                ('sub_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='subpd_id',
            field=models.ForeignKey(db_column='subpd_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_product', to='user.sub_pd'),
        ),
    ]
