# Generated by Django 4.1.1 on 2022-10-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_subscription_delete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delete_time',
            field=models.DateTimeField(null=True),
        ),
    ]
